run:
  timeout: 5m
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        exclude: ^docs/

  - repo: https://github.com/golangci/golangci-lint
    rev: "v1.43.0"
    hooks:
      - id: golangci-lint

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: "ff05dff219bf08fb704e470117650205b8d1e8af"
    hooks:
      - id: go-mod-tidy

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.62.3"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint

  - repo: local
    hooks:
      - id: goreleaser-check
        name: Run goreleaser check
        description: Check if GoReleaser configuration is valid
        language: system
        entry: goreleaser check
        files: ".goreleaser.yaml"
        pass_filenames: false

  - repo: local
    hooks:
      - id: checkmake
        name: Run checkmake
        description: Run checkmake against Makefile
        language: system
        entry: checkmake
        files: "Makefile"
        pass_filenames: true

  - repo: local
    hooks:
      - id: go-generate
        name: Run go generate
        description: "Run go generate"
        entry: go generate ./...
        language: "system"
        pass_filenames: false
