name: Checks

on:
  pull_request:
  push:
    branches: [trunk]

env:
  GO_VERSION: "^1.19.0"
  GORELEASER_VERSION: latest

jobs:
  pre-commit:
    name: Run linters with pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Install checkmake
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          go install github.com/mrtazz/checkmake/cmd/checkmake@ca982aef0af387413edc4b515880bef071730dea
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: ${{env.GORELEASER_VERSION}}
          install-only: true
      - uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.34.1
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0

  tests-ubuntu:
    name: Run acceptance tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{env.GO_VERSION}}
      - run: sudo apt-get install -y sl
      - run: |
          git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.9.0
          . $HOME/.asdf/asdf.sh
          make TESTARGS="-tags=apt" testacc

  tests-macos:
    name: Run acceptance tests on macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{env.GO_VERSION}}
      - run: brew install sl
      - run: |
          git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.9.0
          . $HOME/.asdf/asdf.sh
          make TESTARGS="-tags=brew" testacc
